apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cdis.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: CDI
    listKind: CDIList
    plural: cdis
    singular: cdi
  scope: Namespaced
  version: v1alpha1
