apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
  template:
    metadata:
      labels:
        name: cdi-operator
    spec:
      serviceAccountName: cdi-operator
      containers:
        - name: cdi-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cdi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cdi-operator"
