kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cdi-operator
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-kubevirt-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: cdi-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cdi-operator
rules:
  - apiGroups:
    - cdi.kubevirt.io
    resources:
    - "*"
    verbs:
    - "*"
