---
- name: Render {{ cdi_namespace }} ResourceQuota deployment yaml
  template:
    src:  cdi-resourcequota.yml
    dest: /tmp/cdi-provision-resourcequota.yml

- name: Create {{ cdi_namespace }} ResourceQuota
  command: "kubectl apply -f /tmp/cdi-provision-resourcequota.yml -n {{ cdi_namespace }}"

- name: Render CDI deployment yaml
  template:
    src:  cdi-controller-deployment.yml
    dest: /tmp/cdi-provision.yml

- name: Create CDI deployment
  command: "kubectl apply -f /tmp/cdi-provision.yml -n {{ cdi_namespace }}"
